### ISSUE TITLE
Additional phase bin output to pa_dist

### ISSUE THREAD

**Issue by srcole** [voytekresearch/pacpy#10]
Low priority, but would be nice.

**Comment by parenthetical-e** [comment]
Why?

**Comment by srcole** [comment]
it's just one line the user would have to do anyway since whenever someone is generating a distribution, they probably want to know what the bins are.
I should have had this originally.

**Comment by parenthetical-e** [comment]
Cool. Makes sense. Add it and merge, my main Cole man.
