### ISSUE TITLE
Travis errors and using conda environments

### ISSUE THREAD

**Issue by mmagnuski** [voytekresearch/pacpy#19]
I took a look at the errors that Travis is spitting out.
I was wondering if they might be related to the fact that you are using both `virtualenv` and `conda` (or is it that travis always uses `virtualenv`?). For example virtualenv usues python 2.7.9, but the miniconda version has python 2.7.10 - so there are actually two python versions on the machine. There is also some noise in the installation process - numpy (version 1.10) is first installed via `conda` but then `pip install -r requirements.txt` uninstalls it and installs the required version 1.9. 
Maybe using conda environments is worth trying out?
For example:
```
conda create -n testenv --yes pip python=2.7
conda update conda --yes
source activate testenv
conda install --yes --file requirements.txt
```
You can also take a look at the [travis script that seaborn is using](https://github.com/mwaskom/seaborn/blob/master/.travis.yml)
I would be happy to help with this, but I am using a Windows machine :cry:

**Comment by parenthetical-e** [comment]
Thanks Mikolaj!  Good eye. I’m now hoping you’re spot on. (It’s a simple answer.)

The Travis script is something I hacked together,  just trying for that 'green bar’ as fast as possible. :) I’ll try conda environs (post-SFN).

**Comment by parenthetical-e** [comment]
Looks like it was was conda/pip install nonsense dance I created in the first .yml draft. Now resolved. Thanks @mmagnuski!

**Comment by mmagnuski** [comment]
:+1:
