### ISSUE TITLE
Remove statsmodels dependency

### ISSUE THREAD

**Issue by parenthetical-e** [voytekresearch/pacpy#2]
I'd like to implement multivar ols in numpy/scipy removing the need for `statsmodels`.  With that done `pacpy` would only have a numpy and scipy dependency, meaning matlab wrapper users could just install anaconda and get to work. While it is not really hard to `conda install statsmodels` it's also not really easy for the command line phobic.

**Comment by parenthetical-e** [comment]
::taps foot waiting::

**Comment by voytek** [comment]
:)

You can get paid, or I can write code. But currently we are not in a
position for both to happen simultaneously. Once this R01 is out, then I
should be free again to actually do science.

::brad

**Comment by srcole** [comment]
::taps foot waiting::

**Comment by parenthetical-e** [comment]
::taps foot waiting::

**Comment by parenthetical-e** [comment]
Removed!
