### ISSUE TITLE
The command "conda update --yes conda" failed

### ISSUE THREAD

**Issue by srcole** [voytekresearch/pacpy#24]

**Comment by mmagnuski** [comment]
I looked at http://conda.pydata.org/docs/travis.html and your Travis script is very similar.
The example is just slightly different here:
```
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
```
Judging from the error on Travis which is `conda: command not found` - maybe the path to conda in your Travis script is incorrect?
