### ISSUE TITLE
binder demo

### ISSUE THREAD

**Issue by srcole** [voytekresearch/pacpy#31]
I made a binder for a demo here:
https://github.com/srcole/pacpybinder

Should we incorporate it into this repo?
Any changes that should be made to it?

**Comment by parenthetical-e** [comment]
1. Defing Awesome!
2. I think we should just leave it a as seperate repo, but link to it from the pacpy README

**Comment by srcole** [comment]
I just updated the example ipynb to be as up-to-date as the binder and reference the binder
