### ISSUE TITLE
small optimization

### ISSUE THREAD

**Issue by Palaeocortex** [voytekresearch/pacpy#40]
Hi! I propose a slight optimization of the surrogate MIs. What do you think about

```python
    # Calculate surrogate MIs
    pacS = np.zeros(n_surr)
    np.random.seed(0)

    loj = np.exp(1j * lo)
    for s in range(n_surr):
        loS = np.roll(loj, np.random.randint(len(lo)))
        pacS[s] = np.abs(np.mean(hi * loS))
```
instead of the original
```python
    # Calculate surrogate MIs
    pacS = np.zeros(n_surr)
    np.random.seed(0)
    for s in range(n_surr):
        loS = np.roll(lo, np.random.randint(len(lo)))
        pacS[s] = np.abs(np.mean(hi * np.exp(1j * loS)))
```

It should not change the algorithm, unless I misunderstood sth. very basic... 

Best,
Christian

**Comment by srcole** [comment]
makes sense. I just pushed the changes. Thanks!

**Comment by mmagnuski** [comment]
Just by the way: is setting the seed necessary? From a user endpoint - I would expect that setting the seed is left to me ("from outside" or by passing an optional parameter). If I wanted for example to compare the variability of results depending on number of permutations - I would not expect that somewhere "down the processing path" the seed is being set (this is especially true if I used pacpy as dependency in some other package).

**Comment by srcole** [comment]
agreed.
