### ISSUE TITLE
tests failing with numpy 1.11

### ISSUE THREAD

**Issue by ignatenkobrain** [voytekresearch/pacpy#42]
https://bugzilla.redhat.com/attachment.cgi?id=1125848

A lot of tests failing with:

```python
>       return x[N:-N]
E       IndexError: invalid slice
```

`N` must be integer as written in docstring, but looks like it is `np.dtype.float`

**Comment by parenthetical-e** [comment]
Thanks for the report. The two maintainers are a little distracted right now :) but we'll address this next week. Didn't want to leave you hanging in the meantime though.

**Comment by parenthetical-e** [comment]
Fixed with version 1.0.2.
