### ISSUE TITLE
BUG: pacpy demo.ipynb

### ISSUE THREAD

**Issue by SherazKhan** [voytekresearch/pacpy#50]
Dear Developers,

I was getting familiar with you great package and was trying to run the notebook (pacpy demo.ipynb), I think there are two small bugs;

**1.** In [58]:
```
spikesAMPA[e][0]<tmax*dt
print neusAMPA[0]
```

tmax was used before it was defined

**2.** In [103]:
```
Fs = 1/dt
f_hi = [80, 200]
cf = mod_f_mu  # mod_f_mu was never defined 
beta_hw = 6
```

mod_f_mu was never defined

Thanks

Sheraz

**Comment by srcole** [comment]
oops, old variables.fixed.
thanks, Sheraz!

**Comment by SherazKhan** [comment]
Thanks!!
