### ISSUE TITLE
Add `filterfn=False` to turn off filtering totally?

### ISSUE THREAD

**Issue by parenthetical-e** [voytekresearch/pacpy#8]
Might be useful, especially for people working with the wrapped packages.

**Comment by srcole** [comment]
Yes. More importantly, I think we should have the option to turn off the filterfn and the hilbert transform. Therefore, the user can input pre-calculated phase and amplitude time series (e.g. using the 'pa_series' function) and then calculate PAC on many segments of that time series without the need to re-filter and re-hilbert each time. Would be much faster for some applications.

**Comment by parenthetical-e** [comment]
Agreed. Do it, but do it on a branch. I wanna peak before we merge this one.

**Comment by srcole** [comment]
I only did this for PLV right now because it'll be tedious to copy it to all of the others and annoying if we have to change it. Can you OK the new PLV (on 'opthilb' branch) before I make those changes and merge?

The new relevant tests are in PLV and pass on my computer.

**Comment by srcole** [comment]
Applied expert mode to the rest and merging after checks pass
